# Generated by Django 4.0 on 2022-02-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='my_img',
            field=models.CharField(default='../static/image/default-profile-icon.jpg', max_length=2000),
        ),
    ]
