# Generated by Django 4.0 on 2022-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_my_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='my_img',
            field=models.CharField(default='../static/image/default-profile-icon.jpg', max_length=500),
        ),
    ]
