# Generated by Django 3.2.5 on 2022-01-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='bio',
            new_name='nickname',
        ),
    ]
